export const SEARCH_MOVIE = 'SEARCH_MOVIE';
export const SEARCH_MOVIES = 'SEARCH_MOVIES';
export const FETCH_MOVIES = 'FETCH_MOVIES';
export const LOADING = 'LOADING';
export const PAGINATION = 'PAGINATION';
export const MOVIE_FROM_ID_LOADED = 'MOVIE_FROM_ID_LOADED';
export const ACTIVE_PAGE_CHANGE = 'ACTIVE_PAGE_CHANGE';
export const GET_MOVIES = 'GET_MOVIES';
